version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: npm run dev -- --hostname 0.0.0.0
    restart: unless-stopped 